find . -iname SegmentReplicationStatsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname DerivativeIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationAllocationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname BooleanTermsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname CorruptedFileIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname DiskThresholdDeciderIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname FullRollingRestartIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname PartitionedRoutingIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RecoveryFromGatewayIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RelocationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationClusterSettingIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationPressureIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SnapshotStatusApisIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname TruncatedRecoveryIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname AliasedIndexDocumentActionsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname AllocationIdIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname BlobStoreIncrementalityIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname BucketScriptIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname BulkRejectionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname CloneSnapshotIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterDisruptionCleanSettingsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterDisruptionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterManagerDisruptionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterShardLimitIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ClusterStatsIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname DiskDisruptionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname GetActionIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname GlobalCheckpointSyncIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname MultiClusterRepoAccessIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname RemoteStoreRestoreIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SegmentReplicationRelocationIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SharedClusterSnapshotRestoreIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname ShrinkIndexIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SingleNodeDiscoveryIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
find . -iname SearchTimeoutIT.java | sed -e 's3/3.3g' | sed -e 's3.java3#3g' | cut -d'#' -f 2 | cut -d'.' -f 2-
